### ISSUE TITLE
Telegram tray icon duplicates

### ISSUE THREAD

**Issue by miguelcanosantana** [martinpl/tray-icons-reloaded#33]
With Telegram on flatpak format (not tested with others), when you restore the minimized Telegram from it's tray icon it duplicates the icon, every time you do the same procedure a new icon gets added.

I'm on Gnome 40 on Fedora 34.

![Captura de pantalla de 2021-04-16 09-17-46](https://user-images.githubusercontent.com/55782155/114986824-c442e980-9e94-11eb-89f5-bc4579b2dc0d.png)

**Comment by hkdd** [comment]
![image](https://user-images.githubusercontent.com/42451637/169715561-4cb66e2d-9715-4ee2-b9db-eee30bc8db8c.png)

Not even sure what the icon is.  Right-clicking does nothing, left clicking duplicates it over and over.

Fedora 36 + x11

edit:  Turns out this was "clipit" I just uninstalled it, but no idea why it was duplicating itself or showing up multiple times.
